### ISSUE TITLE
Missing almost all web assets

### ISSUE THREAD

**Issue by trullock** [keeshii/wsquiz#1]
Repro steps:

Clone repo
Follow readme
Launch `localhost:8080`
Observe console errors and non-working app

:(

**Comment by keeshii** [comment]
Hi,
the repository is quite old, but I still managed to compile it and make it run with node 12. This is what I have done after cloning the repo:

#### installing tools ###
```
npm install
npm install grunt-cli
npm install bower
npx bower install   <--- there is 'npx' in this line, to call locally installed bower
```
#### Compiling
This part is a little tricky, because the current version of jslint finds many errors in the code. I had to disable it in Gruntfile.js - I have removed 'jslint' from the line 323. After that the compilation ends successfully:
```
npx grunt
```
#### Serving
Finally start the service:
```
npm start
```

Hope it helps.

**Comment by keeshii** [comment]
I have updated the README file, to make setup clearer. I have also fixed the jslint dependency, so the code compiles well without any hacks.

Let me know if you still have problems? If not, I will close the issue.

**Comment by trullock** [comment]
Thanks, I'll give it a try. I followed the readme so if those steps were missing then thats probably what my issue was :)
